Repository ISF-DDU/ISF-website, pull requests merged in 2023-10, with the labels that each got.

#4 styled navbar
  src/components/Navbar.jsx
  src/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#12 Home page style changed for responsive design , fixed css .
  src/components/HomeCrousel.jsx
  src/pages/Home.jsx
  yarn.lock
Labels: bug, hacktoberfest, hacktoberfest-accepted

#17 #14-created-about-page
  package-lock.json
  package.json
  src/images/iete-core-team-2.jpg
  src/images/iete-full-team.jpg
  src/index.css
  src/pages/About.jsx
  src/pages/Home.jsx
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
